<?php
/**
 * Books social network
 *
 * LICENSE: Closed source
 *
 * @copyright  2008 Dikun Maxim
 * @version    $Id$
 */
?>
<div class="auth-info">
    <?php if (!$this->isLoggedIn): ?>
        <?= $this->form; ?>
        Нет аккаунта? <br /><a href="<?= $this->url(array('action' => 'registration'), 'auth'); ?>">Зарегистрируйся!</a>
    <?php else: ?>
        <div style="text-align: center;">
            Привет,
            <h2><?= $this->profileLink($this->login); ?></h2>
            <a href="<?= $this->url(array(), 'mail'); ?>">Почта</a><br />
            <a href="<?= $this->url(array('action' => 'logout'), 'auth'); ?>">Выйти</a>
        </div>
    <?php endif; ?>
</div>