<?php
/**
 * Books social network
 *
 * LICENSE: Closed source
 *
 * @copyright  2008 Dikun Maxim
 * @version    $Id$
 */
?>
<div class="auth-info">
    <?php if (!$this->isLoggedIn): ?>
        <?= $this->form; ?>
        Нет аккаунта? <br /><a href="<?= $this->url(array('controller' => 'auth', 'action' => 'registration')); ?>">Зарегистрируйся!</a>
    <?php else: ?>
        <div style="text-align: center;">
            Привет,
            <h2><?= $this->profileLink($this->login); ?></h2>
            <ul>
                <li><a href="<?= $this->url(array('controller' => 'mail'), true); ?>">Почта</a></li>
                <li><a href="<?= $this->url(array('controller' => 'friends'), true); ?>">Друзья</a></li>
                <li><a href="<?= $this->url(array('controller' => 'settings'), true); ?>">Настройка</a></li>
                <li><a href="<?= $this->url(array('controller' => 'auth', 'action' => 'logout'), true); ?>">Выйти</a></li>
            </ul>
        </div>
    <?php endif; ?>
</div>