<?php
/**
 * Books social network
 *
 * LICENSE: Closed source
 *
 * @copyright  2008 Dikun Maxim
 * @version    $Id:$
 */
?>
<h1>Добавить произведение в библиотеку</h1>

<form method="post" action="<?= $this->url(array('action' => 'add-process')); ?>">
    <span title="Достаточно указать любого из авторов, если их несколько">Автор</span>:
    <input id="author" name="author" /><br />

    Название: <input id="title" name="title" /><br />
    <input type="submit" value="Добавить" />
</form>
