<?php
/**
 * Books social network
 *
 * LICENSE: Closed source
 *
 * @copyright  2008 Dikun Maxim
 * @version    $Id:$
 */
?>
<?php echo $this->doctype() ?>
<html>
<head>
  <?= $this->headTitle(); ?>
  <?= $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8'); ?>
  <?= $this->headLink()->appendStylesheet('/styles/main.css'); ?>
  <?= $this->headScript(); ?>
</head>
<body class="tundra">
    <?php
        $login = Zend_Controller_Front::getInstance()->getRequest()->getParam('login');
    ?>
    <div class="left-col">
        <?= $this->action('show-login', 'auth'); ?>
        <div class="navigation">
            <?= $this->navigationLink(null, 'Книги',
                    $this->url(array('action' => 'library'), 'default')); ?>
            <?= $this->navigationLink('profile', 'Профиль',
                    $this->url(array('controller' => 'user',
                                    'action' => 'profile',
                                    'login' => $login), 'user')); ?>
            <?= $this->navigationLink('blog', 'Журнал',
                    $this->url(array('controller' => 'user',
                                    'action' => 'blog',
                                    'login' => $login), 'user')); ?>
        </div>
    </div>
    <div id="main-container" class="main-container">
        <?= $this->topMenu(); ?>
        <div class="content">
            <?= $this->layout()->content; ?>
            <?= $this->inlineScript() ?>
        </div>
    </div>
</body>
</html>