<?php
/**
 * Books social network
 *
 * LICENSE: Closed source
 *
 * @copyright  2008 Dikun Maxim
 * @version    $Id$
 */
?>
<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
<head>
  <?= $this->headTitle(); ?>
  <?= $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8'); ?>
  <?= $this->headLink()->prependStylesheet('/styles/main.css'); ?>
  <?= $this->headScript(); ?>
  <?= $this->jQuery(); ?>
</head>
<body>
    <div class="left-col">
        <?php
            echo $this->action('show-login', 'auth'); // TODO Rewrite with helper
        ?>
        <div class="navigation">
            <?= $this->navigationLink(null, 'Книги',
                    $this->libraryUrl(null, false, false)); ?>
        </div>
    </div>
    <div id="main-container" class="main-container">
        <?= $this->topMenu(); ?>
        <div class="content">
            <?= $this->layout()->content; ?>
            <?= $this->inlineScript() ?>
        </div>
    </div>
</body>
</html>