<?php
/**
 * Books social network
 *
 * LICENSE: Closed source
 *
 * @copyright  2008 Dikun Maxim
 * @version    $Id:$
 */
?>
<?php echo $this->doctype() ?>
<html>
<head>
  <?= $this->headTitle(); ?>
  <?= $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8'); ?>
  <?= $this->headLink()->appendStylesheet('/styles/main.css'); ?>
</head>
<body>
    <div id="main-container" class="main-container full-width">
        <div class="content">
            <?= $this->layout()->content; ?>
        </div>
    </div>
</body>
</html>