<?php
/**
 * Books social network
 *
 * LICENSE: Closed source
 *
 * @copyright  2008 Dikun Maxim
 * @version    $Id:$
 */
?>
<h1><?= $this->vars['main']; ?></h1>
Сайт
<?php foreach ($this->items as $item): ?>
    <div>
    <div align="center">
        <?= $item->getItemText()->getRevision()->getMdate()->toString(null, null, 'ru') ?>
    </div>
    <?= $item->getItemText()->getRevision()->getText() ?>
    </div>
<?php endforeach; ?>
