<?php
/**
 * Books social network
 *
 * LICENSE: Closed source
 *
 * @copyright  2008 Dikun Maxim
 * @version    $Id$
 */
$this->jQuery()->addJavascriptFile('/scripts/writeboard.js');
$this->jQuery()->onLoadCaptureStart(); ?>
    Writeboard.id = <?= $this->id; ?>;
    Writeboard.load();
    $('.message .delete').livequery("click", Writeboard.deleteHandler);
<?php $this->jQuery()->onLoadCaptureEnd(); ?>

<div class="writeboard">
    <?php if ($this->isAllowed('writeboard', 'add')):
        $this->jQuery()->onLoadCaptureStart(); ?>
            $('#writeboard-message').keyup(Writeboard.textareaKeyupHandler);
            $('#writeboard-write-link').click(Writeboard.showTextareaHandler);
            $('#writeboard-submit').click(Writeboard.addHandler);
        <?php $this->jQuery()->onLoadCaptureEnd(); ?>

        <a id="writeboard-write-link" href="#">Оставить сообщение</a>
        <div id="writeboard-input">
            <p>Еще можно написать <span id="writeboard-length">1000</span> символов.
            <textarea id="writeboard-message" rows="4" cols="70" name="message"></textarea>
            <input type="hidden" name="id" value="<?= $this->id; ?>" />
            <input id="writeboard-submit" type="button" value="Написать" /></p>
        </div>
    <?php endif; ?>

    <div class="messages" id="writeboard-<?= $this->id; ?>">
        <img src="/images/ajax-loader.gif" /> Загружается...
    </div>
</div>
