<h1><?= $this->title->getName(); ?></h1>
<h2><?= $this->author->getName(); ?></h2>

<?php if ($this->title->getFrontDescription() != ''): ?>
<p><?= $this->title->getFrontDescription(); ?></p>
<p><a href="#">Читать далее...</a> | <a href="#">Редактировать</a> </p>
<?php else: ?>
<p>У нас пока нет описания этого произведения. <a href="#">Есть желание помочь?</a></p>
<?php endif; ?>


<div class="profile-info">
    <div class="header">
        <?php if ($this->isAllowed($this->title->getWriteboard(), "delete")): ?>
        <div class="edit">
            [чистить]
        </div>
        <?php endif; ?>
        Доска сообщений
    </div>
    <div class="body">
        <?= $this->action('show', 'writeboard', null, array('writeboard' => $this->title->getWriteboard())); ?>
    </div>
</div>