<?php
/**
 * Books social network
 *
 * LICENSE: Closed source
 *
 * @copyright  2008 Dikun Maxim
 * @version    $Id$
 */
?>
<h1>Предложения дружбы</h1>

<h2>Полученые запросы</h2>
<?= $this->usersList($this->receivedRequests, App_View_Helper_UsersList::LIST_RECEIVED_REQUESTS,
    'Нет полученых запросов'); ?>

<h2>Отправленые запросы</h2>
<?= $this->usersList($this->sentRequests, App_View_Helper_UsersList::LIST_SENT_REQUESTS,
    'Нет отправленых запросов'); ?>
