<div class="writeboard">
    <?php if ($this->isAllowed('writeboard', 'add')): ?>
        <a href="#" onclick="document.getElementById('writeboard-input').style.display = 'block'; this.style.display = 'none'; return false;">Оставить сообщение</a>
        <div id="writeboard-input">
            <form action="<?= $this->url(array('action' => 'add'), 'writeboard'); ?>" method="post">
                Еще можно написать <span id="writeboard-length">1000</span> символов.
                <textarea rows="4" name="message"></textarea>
                <input type="hidden" name="id" value="<?= $this->id; ?>" />
                <input type="submit" value="Написать" />
            </form>
        </div>
    <?php endif; ?>
    
    <div class="messages">
        <?php foreach($this->messages as $message): ?>
            <?php $login = $message->getWriteboardWriter()->getLogin(); ?>
            <div class="message">
                <div class="message-date">
                    <?= $message->getMessageDate()->toRelativeString(); ?>
                </div>
                <div class="message-user">
                    <?php if ($this->login != $login): ?>
                    <a href="<?= $this->url(array('controller' => 'user',
                                                  'action' => 'profile',
                                                  'login' => $login
                                                 ), 'user'); ?>" title="Посмотреть профиль <?= $login; ?>">
                        <?= $login; ?>
                    </a>
                    <?php else: ?>
                        <?= $login; ?>
                    <?php endif; ?>
                </div>
                    <?php if ($this->isAllowed($message, 'delete')): ?>
                        <form action="<?= $this->url(array('action' => 'delete'), 'writeboard'); ?>" method="post">
                            <input type="hidden" name="id" value="<?= $this->id ?>" />
                            <input type="hidden" name="messageid" value="<?= $message->getId() ?>" />
                            <input type="submit" value="удалить" />
                        </form>
                    <?php endif; ?>
                <div class="message-content">
                    <?= $message->getMessage(); ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>