<? // setup data store for FilteringSelect ?>
<div dojoType="dojox.data.QueryReadStore" jsId="authorStore"
    url="/ajax/author-suggest"
    requestMethod="get"></div>

<? // Input element: ?>
State: <input id="state" dojoType="dijit.form.ComboBox"
    store="authorStore" pageSize="10" hasDownArrow="false" autoComplete="false" 
    searchDelay="300" />

<? // setup required dojo elements:
$this->dojo()->enable()
             ->setDjConfigOption('parseOnLoad', true)
             ->requireModule('dijit.form.ComboBox')
             ->requireModule('dojox.data.QueryReadStore'); ?>

