<? // setup data store for FilteringSelect ?>
<div dojoType="dojo.data.ItemFileReadStore" jsId="stateStore"
    url="/ajax/author-suggest"
    requestMethod="get"></div>

<? // Input element: ?>
State: <input id="state" dojoType="dijit.form.FilteringSelect"
    store="stateStore" pageSize="5" />

<? // setup required dojo elements:
$this->dojo()->enable()
             ->setDjConfigOption('parseOnLoad', true)
             ->requireModule('dijit.form.FilteringSelect')
             ->requireModule('dojo.data.ItemFileReadStore'); ?>

