<?php
/**
 * Books social network
 *
 * LICENSE: Closed source
 *
 * @copyright  2008 Dikun Maxim
 * @version    $Id$
 */
?>
    <div class="photo-placeholder">
        Здесь<br />
        могло<br />
        быть<br />
        ваше<br />
        фото<br />
    </div>
    <div class="profile-stats">
        Чего-то сделал... Еще чего-то... Ничего важного и интересного
    </div>
    <div class="profile-actions">
        <ul>
            <li><a href="<?= $this->url(array(
                              'controller' => 'mail',
                              'action' => 'new')); ?>?to=<?= $this->user->getLogin()?>">Написать сообщение</a></li>
            <li><a href="<?= $this->url(array(
                              'controller' => 'friends',
                              'action' => 'confirm',
                              'user' => $this->user->getLogin()
                          )); ?>">Добавить в друзья</a></li>
        </ul>
    </div>
    <div class="profile-info">
        <div class="header">
            <?php if ($this->isAllowed("profile", "edit")): ?>
            <div class="edit">
                [редактировать]
            </div>
            <?php endif; ?>
            О себе.
        </div>
        <div class="body">
            Тут должна быть какая-то инфа.<br />
            Тут должна быть какая-то инфа.<br />
            Тут должна быть какая-то инфа.<br />
            Тут должна быть какая-то инфа.<br />
            Тут должна быть какая-то инфа.<br />
            Тут должна быть какая-то инфа.<br />
            Тут должна быть какая-то инфа.<br />
            Тут должна быть какая-то инфа.<br />
            Тут должна быть какая-то инфа.<br />
            Тут должна быть какая-то инфа.<br />
        </div>
    </div>
    <div class="profile-info">
        <div class="header">
            <?php if ($this->isAllowed("profile", "edit")): ?>
            <div class="edit">
                <a href="<?= $this->url(array('controller' => 'bookshelf', 'action' => 'add')); ?>">[добавить]</a>
                [редактировать]
            </div>
            <a href="<?= $this->url(array('action' => 'bookshelf')); ?>">Книжная полка</a>
            <?php else: ?>
            Книжная полка
            <?php endif; ?>

        </div>
        <div class="body">
            <?php $titles = $this->user->getBookshelf()->getTitles(); ?>
            <?php foreach ($titles as $title): ?>
                <?= $this->titleLink($title); ?><br />
            <?php endforeach; ?>
        </div>
    </div>
    <div class="profile-info">
        <div class="header">
            <?php if ($this->isAllowed($this->writeboard, "delete")): ?>
            <div class="edit">
                [чистить]
            </div>
            <?php endif; ?>
            Доска сообщений
        </div>
        <div class="body">
            <?= $this->action('show', 'writeboard', null, array('writeboard' => $this->writeboard)); ?>
        </div>
    </div>
