<?php
/**
 * Books social network
 *
 * LICENSE: Closed source
 *
 * @copyright  2008 Dikun Maxim
 * @version    $Id:$
 */
?>
<h1><?= $this->title->getName(); ?></h1>
<h2><?= $this->author->getName(); ?></h2>
<h4>Информация</h4>

<p>
<?= $this->title->getText(); ?>
</p>

<?php if ($this->isAllowed('wiki', 'edit')): ?>
    <a href="<?= $this->url(array('action' => 'wiki-edit')); ?>">Редактировать</a>
<?php endif; ?>