<?php if (!$this->isLoggedIn): ?>
<form action="<?= $this->url(array('controller' => 'auth', 'action' => 'login'), 'default'); ?>" method="post">
	<table>
		<tr>
			<td style="text-align: right;"><label for="login">Логин:</label></td>
			<td><input id="login" type="text" name="login" class="loginfield" /></td>
		</tr>
		<tr>
			<td style="text-align: right;"><label for="password">Пароль:</label></td>
			<td><input id="password" type="password" name="password" class="loginfield" /></td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td style="text-align: right;"><input type="submit" value="Ага, это я" class="loginfield" /></td>
		</tr>
	</table>
</form>
<?php else: ?>
<div align="center">
    Привет,
    <h2><a href="<?= $this->url(array('controller' => 'user', 'action' => 'profile', 'login' => $this->login), 'user'); ?>"><?= $this->login ?></a></h2>
    <a href="<?= $this->url(array('controller' => 'auth', 'action' => 'logout'), 'default'); ?>">Выйти</a>
</div>
<?php endif; ?>