<?php if ($this->frontImage === false): ?>
    <div class="photo-placeholder">
        Здесь<br />
        могла<br />
        быть<br />
        фотография<br />
        автора<br />
    </div>
<?php else: ?>
    <div class="photo-image">
        <img src="<?= $this->frontImage->getPath(); ?>" />
    </div>
<?php endif; ?>
<h1><?= $this->author->getName(); ?></h1>
<?php if ($this->author->getFrontDescription() != ''): ?>
<p><?= $this->author->getFrontDescription(); ?></p>
<p>
    <a href="<?= $this->url(array('author' => $this->author->getName(), 'action' => 'wiki'), 'libraryauthoraction') ?>">
        Читать далее...
    </a>
    <?php if ($this->isAllowed('wiki', 'edit')): ?>
     |
    <a href="<?= $this->url(array('author' => $this->author->getName(), 'action' => 'wiki-edit'), 'libraryauthoraction') ?>">
        Редактировать
    </a>
    <?php endif; ?>
</p>
<?php else: ?>
<p>У нас пока нет описания этого автора.
    <?php if ($this->isAllowed('wiki', 'edit')): ?>
        <a href="<?= $this->url(array('author' => $this->author->getName(), 'action' => 'wiki-edit'), 'libraryauthoraction') ?>">Есть желание помочь?</a>
    <?php endif; ?>
</p>
<?php endif; ?>

<div class="author-titles">
    <?php $this->titles = $this->author->getTitles(); ?>
    <div class="header">
        Произведения (<?= count($this->titles); ?>)
    </div>
    <div class="body">
        <?php foreach ($this->titles as $title): ?>
            <a href="<?= $this->url(array('author' => $this->author->getName(),
                'title' => $title->getName()), 'librarytitle'); ?>"><?= $title->getName() ?></a><br />
        <?php endforeach; ?>
    </div>
</div>

<div class="profile-info">
    <div class="header">
        <?php if ($this->isAllowed($this->author->getWriteboard(), "delete")): ?>
        <div class="edit">
            [чистить]
        </div>
        <?php endif; ?>
        Доска сообщений
    </div>
    <div class="body">
        <?= $this->action('show', 'writeboard', null, array('writeboard' => $this->author->getWriteboard())); ?>
    </div>
</div>
