<?php
/**
 * Books social network
 *
 * LICENSE: Closed source
 *
 * @copyright  2008 Dikun Maxim
 * @version    $Id:$
 */
?>
<h1><?= $this->author->getName(); ?></h1>
<h4>Информация</h4>

<form method="post" action="<?= $this->url(array('action' => 'wiki-save')); ?>">
<textarea rows="20" style="width: 100%" name="text"><?= $this->author->getText(); ?></textarea>
<input type="submit" value="Сохранить" />
</form>

