    <div class="photo-placeholder">
        Здесь<br />
        могло<br />
        быть<br />
        ваше<br />
        фото<br />
    </div>
    <div class="profile-stats">
        Чего-то сделал... Еще чего-то... Ничего важного и интересного
    </div>
    <div class="profile-info">
        <div class="header">
            <?php if ($this->isAllowed("profile", "edit")): ?>
            <div class="edit">
                [редактировать]
            </div>
            <?php endif; ?>
            О себе.
        </div>
        <div class="body">
            Тут должна быть какая-то инфа.<br />
            Тут должна быть какая-то инфа.<br />
            Тут должна быть какая-то инфа.<br />
            Тут должна быть какая-то инфа.<br />
            Тут должна быть какая-то инфа.<br />
            Тут должна быть какая-то инфа.<br />
            Тут должна быть какая-то инфа.<br />
            Тут должна быть какая-то инфа.<br />
            Тут должна быть какая-то инфа.<br />
            Тут должна быть какая-то инфа.<br />
        </div>
    </div>
    <div class="profile-info">
        <div class="header">
            <?php if ($this->isAllowed("profile", "edit")): ?>
            <div class="edit">
                [редактировать]
            </div>
            <?php endif; ?>
            Библиотека
        </div>
        <div class="body">
            <?php $titles = $this->user->getBookshelf()->getTitles(); ?>
            <?php foreach ($titles as $title): ?>
                <?= $this->titleLink($title); ?><br />
            <?php endforeach; ?>
        </div>
    </div>
    <div class="profile-info">
        <div class="header">
            <?php if ($this->isAllowed($this->writeboard, "delete")): ?>
            <div class="edit">
                [чистить]
            </div>
            <?php endif; ?>
            Доска сообщений
        </div>
        <div class="body">
            <?= $this->action('show', 'writeboard', null, array('writeboard' => $this->writeboard)); ?>
        </div>
    </div>
