<?php
/**
 * Books social network
 *
 * LICENSE: Closed source
 *
 * @copyright  2008 Dikun Maxim
 * @version    $Id$
 */

$this->headLink()->appendStylesheet('/styles/mail.css');

$htmlFilter = new Zend_Filter_HtmlEntities(ENT_COMPAT, 'UTF-8');
?>
<a href="<?= $this->url(array('param' => '')); ?>">&lt;&lt; Назад</a>

<div class="mail-messages">
    <?php
    $messagesCount = count($this->messages);
    $i = 0;
    $newFound = false;
    foreach ($this->messages as $message):
        ++$i; ?>
        <div<?= $message['from_user1'] == $this->youFirst ? ' class="your-message"' : ''; ?>>
            <?php // Show anchor 'new-message' on first new (but not your) or last message
            if (($i == $messagesCount || ($message['is_new'] && $message['from_user1'] == $this->youFirst))
                && !$newFound ): ?>
                <a name="new-message"></a>
            <?php
                $newFound = true;
            endif;
            ?>
            <p class="info">
                <b><?= $message['from_user1'] ? $this->name1 : $this->name2; ?></b>,
                <i><?= $message['date']; ?></i>
            </p>
            <p><?= nl2br($htmlFilter->filter($message['message'])); ?></p>
        </div>
    <?php endforeach;?>

    <?= $this->form; ?>
</div>

