<?php echo $this->doctype() ?>
<html>
<head>
  <?= $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8'); ?>
  <?= $this->headLink()->appendStylesheet('/public/css/main.css'); ?>
  <?= $this->headTitle(); ?>
</head>
<body>
	<?php
	    $login = Zend_Controller_Front::getInstance()->getRequest()->getParam('login');
	?>
	<div class="left-col">
	<div class="login"><?= $this->action('show-login', 'auth'); ?></div>
	<div class="navigation">
	    <?= $this->navigationLink(null, 'Книги',
	            $this->url(array(), 'librarymain')); ?>
	    <?= $this->navigationLink('profile', 'Профиль',
	            $this->url(array('controller' => 'user',
	                             'action' => 'profile',
	                             'login' => $login), 'user')); ?>
	    <?= $this->navigationLink('blog', 'Журнал',
	            $this->url(array('controller' => 'user',
	                             'action' => 'blog',
	                             'login' => $login), 'user')); ?>
	</div>
	</div>
	<div class="content">
	    <?= $this->layout()->content; ?>
	</div>
</body>
</html>